language: python
dist: xenial
python: "3.7"
script:
  - ./make_zipapp.py
  - env MODE=release ./test.bats
  - gpg2 --import release_key.asc
  - gpg2 --verify httpshare.pyz{.asc,}
before_deploy:
  - git config --local user.name "Julie Bettens"
  - git config --local user.email "bbjubjub2494@users.noreply.github.com"
  - export TRAVIS_TAG=$(cd src; python -c "import httpshare; print(httpshare.version)")
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  file:
    - httpshare.pyz
    - httpshare.pyz.asc
  skip_cleanup: true
  api_key:
    secure: "YaNfKxz+VH8pKf8JnErV0TM6yILppYAh3pRAEVsFcXr67aN6Nv9C9LCB299l5lF7nKf1B093TsBmPQLxUmUGwIpn3oAxY2umuHlYOoi31kn8mjpyZwtQhHCftxQN7/wNRAFwXqyQa6MrN7DJ25j8HQYpIdtCQxu7O6Tro75VEUTBPlyvM97D/hb0sqrFmOJt0xa+rEa7Dfnd/o04BuTjIyaELvieBKZYFUVc8y8rbz+GZ/vtHPHbwbmoOs+rMJjgZl5uu1WxPaAOYjcNfVuL1dOJfLmttb0EGJwYZ+Zj4ppRGYkejyNEVjmwSsjpfe+BTuFqCx2uBPCK0krKX0Ptp2+CVhjgNf+FgYa/5f4eSEwf60btUbcMrnKP5usIcI5SDrQFkiaokTHnL5Xakxbd2vQnjb7+lIyz7C9pZ8nZbbN7l+Ui5U1GuYMSt++7mYFLPX2XGPN4zJo7lVGu5mR/zmIfiJukmqkYAK3jKsKN2v5xOLDyZwkd71zGMFElHOErgTF29NHqHKxgWVUxnD30Fqnv0ISkmPWgxKDyVGY76Rzf2aLnDSjpnac/0V9Aj0a5piGxW0+IwtAMt+iEXBm6YZs060aBCFob7k5GScizMJZ+AgndFl5blG0eMbAQGKUNv8CSspB8Ueg14rqw9AokFabyKCOIbEmUz//Y2L5ajEo="
  on:
    repo: bbjubjub2494/httpshare
    branch: releases
