language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "pypy"
sudo: false # Use container-based infrastructure
install:
  - "pip install mock"
script: "python -m unittest discover -p *_test.py"
